# Generated by Django 4.2.5 on 2023-09-13 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_term_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.CharField(default='FAKE_9478344', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, unique=True)),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.term')),
            ],
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_term', to='api.term')),
                ('parent_term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_term', to='api.term')),
            ],
        ),
    ]
