# Generated by Django 4.2.5 on 2023-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_synonym_term_alter_term_id_synonymandterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.CharField(default='FAKE_9371101', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='term',
            name='label',
            field=models.TextField(),
        ),
    ]
