# Generated by Django 4.2.5 on 2023-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_term_id_alter_term_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.CharField(default='FAKE_327895', max_length=32, primary_key=True, serialize=False),
        ),
    ]
