# Generated by Django 4.2.5 on 2023-09-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_term_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='synonyms',
            field=models.ManyToManyField(to='api.synonym'),
        ),
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.CharField(default='FAKE_7066019', max_length=32, primary_key=True, serialize=False),
        ),
    ]
