# Generated by Django 4.2.5 on 2023-09-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_term_synonyms_alter_term_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='parents',
            field=models.ManyToManyField(to='api.term'),
        ),
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.CharField(default='FAKE_7792103', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='SynonymAndTerm',
        ),
    ]
