# Generated by Django 4.2.5 on 2023-09-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_term_parents_alter_term_id_delete_synonymandterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.CharField(default='FAKE_1469259', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='term',
            name='parents',
            field=models.ManyToManyField(related_name='children', to='api.term'),
        ),
        migrations.DeleteModel(
            name='Ontology',
        ),
    ]
