# Generated by Django 4.2.5 on 2023-09-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_synonym_label_alter_term_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.CharField(default='FAKE_3860763', max_length=32, primary_key=True, serialize=False),
        ),
    ]
